# apiVersion: v1
# kind: Namespace
# metadata:
#   name: springboot-react-app
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: app-data-pvc
#   namespace: springboot-react-app
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: microservice1
#   namespace: springboot-react-app
#   labels:
#     app: microservice1
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: microservice1
#   template:
#     metadata:
#       labels:
#         app: microservice1
#     spec:
#       containers:
#       - name: microservice1
#         image: kaiohenricunha/microservice1:latest
#         ports:
#         - containerPort: 8080
#         volumeMounts:
#         - name: app-data
#           mountPath: /app/data
#         resources:
#           requests:
#             memory: "256Mi"
#             cpu: "250m"
#           limits:
#             memory: "256Mi"
#       volumes:
#       - name: app-data
#         persistentVolumeClaim:
#           claimName: app-data-pvc
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: microservice1
#   namespace: springboot-react-app
#   labels:
#     app: microservice1
# spec:
#   selector:
#     app: microservice1
#   ports:
#     - protocol: TCP
#       port: 8080
#       targetPort: 8080
#   type: LoadBalancer
# ---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: microservice1-hpa
#   namespace: springboot-react-app
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: microservice1
#   minReplicas: 1
#   maxReplicas: 5
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 100 # % o requests
#   - type: Resource
#     resource:
#       name: memory
#       target:
#         type: Utilization
#         averageUtilization: 85
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: inventory-service
#   namespace: springboot-react-app
#   labels:
#     app: inventory-service
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: inventory-service
#   template:
#     metadata:
#       labels:
#         app: inventory-service
#     spec:
#       containers:
#       - name: inventory-service
#         image: kaiohenricunha/inventory-service:latest
#         ports:
#         - containerPort: 8081
#         resources:
#           requests:
#             memory: "256Mi"
#             cpu: "250m"
#           limits:
#             memory: "256Mi"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: inventory-service
#   namespace: springboot-react-app
#   labels:
#     app: inventory-service
# spec:
#   selector:
#     app: inventory-service
#   ports:
#     - protocol: TCP
#       port: 8081
#       targetPort: 8081
#   type: ClusterIP
# ---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: inventory-service-hpa
#   namespace: springboot-react-app
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: inventory-service
#   minReplicas: 1
#   maxReplicas: 5
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 100
#   - type: Resource
#     resource:
#       name: memory
#       target:
#         type: Utilization
#         averageUtilization: 95
