global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'microservice1'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['microservice1:8080']

  - job_name: 'microservice2'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['microservice2:8081']
